post_install do |installer|
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            if config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'].to_f < 18.0
                config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '18.0'
            end
        end
    end
end

inhibit_all_warnings!
use_frameworks! :linkage => :static
source 'https://cdn.cocoapods.org/'
source 'https://github.com/lovexiaoxia/MOKO-Specs.git'

platform :ios, '18.0'

target 'MKLoRaWAN-PB_Example' do
  pod 'MKLoRaWAN-PB', :path => '../'
end
